services:
    db:
        image: mariadb:10.6
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
          - './docker/mariadb/db/mysql:/var/lib/mysql'
          - './docker/mariadb/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf'
        networks:
            - servizi_web
    redis-cache:
        image: 'redis:7.2'
        environment:
          - TZ=Europe/Rome
          - REDIS_MAXMEMORY_POLICY=allkeys-lru
        command: ["redis-server", "--appendonly", "no", "--save", "", "--maxmemory", "2048mb", "--maxmemory-policy", "allkeys-lru"]
        networks:
          - servizi_web
    redis-sessioni:
        image: 'redis:7.2'
        environment:
          - TZ=Europe/Rome
          - REDIS_MAXMEMORY_POLICY=volatile-lru       # Politica di gestione della memoria
        command: ["redis-server", "--appendonly", "no", "--save", "", "--maxmemory", "4096mb", "--maxmemory-policy", "volatile-lru"]
        networks:
          - servizi_web
    fpm:
        build: 'docker/php/'
        environment:
          - TZ=Europe/Rome
        volumes:
            - './www:/var/www/html'
            - './docker/php/conf/php.ini:/usr/local/etc/php/php.ini'
            - './docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf'
        networks:
          - servizi_web
        user: "1000:1000"

    web:
        image: nginx:1.19.9-alpine
        volumes:
            - './www:/var/www/html'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        networks:
          - servizi_web
        ports:
          - 80:80
        depends_on:
            fpm:
                condition: service_started
        environment:
            - VIRTUAL_HOST=localhost
            - VIRTUAL_PORT=80
            - HTTPS_METHOD=noredirect
            - TZ=Europe/Rome


    opensearch:
        build: 'docker/opensearch/'
        image: 'opensearchproject/opensearch:2.12.0'
          #volumes:
          #- './docker/elasticsearch/default.yml:/usr/share/elasticsearch/config/defautl.yml'
          #- './docker/elasticsearch/log.log:/usr/share/elasticsearch/logs/esmalfatti-docker.log'
          #- './docker/elasticsearch/data:/usr/share/opensearch/data'
        networks:
          - servizi_web
        ulimits:
          memlock:
              soft: -1
              hard: -1
          nofile:
              soft: 65536
              hard: 65536
        environment:
          - TZ=Europe/Rome
          - cluster.name=es-docker
          - node.name=node1
          - bootstrap.memory_lock=false
          - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx2g"
          - discovery.type=single-node
          - "cluster.routing.allocation.disk.threshold_enabled=false"
          - "index.blocks.read_only_allow_delete"
          - plugins.security.disabled=true
          - OPENSEARCH_INITIAL_ADMIN_PASSWORD=jsjdjfSDFGRRdwetdxsefUHGxzBikID12fGG
          - "max_map_count=262144"
        mem_limit: 2G

volumes:
    db-data: {  }
networks:
  servizi_web:
    driver: bridge
